config/routes.rb
PersonalizedLearning::Application.routes.draw do

  resources :users, only: [:new, :show, :create, :destroy, :edit, :update] do
    member do
      put :answer_task
      put :answer_questionnaire
      get :edit_traits
      put :update_traits
      get :move_to_next_step
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks
  resources :traits, only: [:new, :edit, :update, :create, :destroy]
  resources :questionnaires
  match "/answers_for_tasks", to: "answers#for_tasks"
  match "/answers_for_questionnaires", to: "answers#for_questionnaires"

  root :to => 'sessions#new'

  match '/home', to: "users#home"
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/admin',   to: 'admin#home'

end

app/models/task.rb
class Task < CustomizableItem
  attr_accessible :material, :name, :step_id, :is_finalized, :questions_attributes

  validates :name, presence: true
  validates :material, presence: true

  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions, :reject_if => lambda { |q| q[:text].blank? }, :allow_destroy => true

  belongs_to :step

  has_many :exons, dependent: :destroy
  accepts_nested_attributes_for :exons, :allow_destroy => true

  def personalizable_content
    material
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include UserTraitsHelper

  before_filter :admin_user, only: [:new, :create, :destroy]
  before_filter :user_signed_in, only: [:show]
  before_filter :build_preview_traits, only: [:new, :edit, :update]

  def show
    fill_user_traits current_user
    @task = Task.find params[:id]
    build_answers @task, current_user
  end

  def new
    @task = Task.new
    build_questions @task, 6, 6
    render :edit
  end

  def edit
    @task = Task.find params[:id]
    build_questions @task, 6, 6
  end

  def update
    @task = Task.find params[:id]
    if @task.update_attributes params[:task]
      flash[:success] = "Task #{@task.name} updated successfully"
    end
    render :edit
  end

  def create
    @task = Task.new(params[:task])
    if @task.save
      flash[:success] = "Task #{@task.name} created successfully"
      redirect_to admin_path
    else
      render :edit
    end
  end

  def destroy
    Task.find(params[:id]).destroy
    flash[:success] = "Task destroyed."
    redirect_to admin_path
  end

  def build_preview_traits
    user= User.find_by_login("testuser")
    fill_user_traits user
    @preview_traits = {}
    Trait.no_options.each do |trait|
      user_trait = user.user_traits.where(trait_id: trait.id).first
      @preview_traits[trait.id] = user_trait.value
    end
    logger.debug @preview_traits
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_exon_fields.html.erb
<div class="exon row-fluid <%= "with_initial_variations" if !form_builder.object.variations.empty? %>">
  <div class='trait span6'>
    <%= form_builder.label :trait_id, form_builder.object.slug %>
    <%= form_builder.collection_select :trait_id, Trait.all, :id, :name, :class => "exon_trait" %>

    <%= form_builder.hidden_field :id %>
    <%= form_builder.hidden_field :slug, :class => "exon_slug" %>
    <%= form_builder.check_box :_destroy, :class => "exon_destroy" %>
  </div>

  <div class="contents span6">
    <%= form_builder.label :traditional_content %>
    <%= form_builder.text_field :traditional_content %>
    <div class="variations">
      <%= form_builder.fields_for :variations do |variation_f| %>
        <%= variation_f.label :content, variation_f.object.option.value %>
        <%= variation_f.text_field :content %>
        <%= variation_f.hidden_field :option_id %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_questions_fieldset.html.erb
<fieldset id="questions">
  <legend>Questions</legend>

  <% form_builder.object.questions.each.with_index do |question,q_index| %>
    <%= form_builder.fields_for :questions, question, child_index: q_index do |question_f| %>
      <div class="row-fluid question_row<%= ' hide' if question_f.object.new_record? %>">
        <div class="question span3">
          <%= question_f.label :text, "question text" %>
          <%= question_f.text_field :text, :class => "question_text", "data-idx" => q_index %>
          <% if !question_f.object.new_record? %>
            <div>
              <%= question_f.check_box :_destroy %>
              <span class="help-inline">Destroy question</span>
            </div>
          <% end %>
        </div>
        <div class="choices span9">
          <label>Choices</label>
          <% question_f.object.choices.each.with_index do |choice, c_index| %>
            <%= question_f.fields_for :choices, choice, child_index: c_index do |choice_f| %>
              <div class="choice_row<%= ' hide' if choice_f.object.new_record? %>">
                <%= choice_f.text_field :text, :class => "choice_text",
                  "data-question-idx" => q_index, "data-idx" => c_index %>
                <% if with_choices_labels %>
                  label :
                  <%= choice_f.text_field :label %>
                <% end %>
                <% if with_correct_checkboxes %>
                  <%= choice_f.check_box :right %>
                  <span class="help-inline">Correct</span>
                <% end %>
                <% if !choice_f.object.new_record? %>
                  <%= choice_f.check_box :_destroy %>
                  <span class="help-inline">Destroy choice</span>
                <% end %>
              </div>
            <% end %>
          <% end %>
          <div>
            <a href="javascript:void(0);" class="new_choice btn">Add a choice</a>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="row-fluid">
    <div class="span3">
      <a href="javascript:void(0);" class="new_question btn">Add a question</a>
    </div>
  </div>
</fieldset>

app/views/tasks/edit.html.erb
<h1><%= @task.new_record? ? "New Task" : "Edit task" %></h1>

<%= form_for(@task) do |f| %>
  <%= render 'shared/error_messages', {object: @task} %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :step_id %>
  <%= f.collection_select :step_id, Step.all, :id, :name %>

  <%= f.label :is_finalized %>
  <%= f.check_box :is_finalized %>

  <div class="row-fluid">
    <div class="span6">
      <%= f.label :material %>
      <%= f.text_area :material, rows: 10, :class => "span12" %>
    </div>
    <div class="span6">
      <label>Material Preview</label>
      <div class="task_material alert alert-info"></div>
    </div>
  </div>

  <fieldset id="exons">
    <legend>Personalizable parts</legend>

    <div class="row-fluid">

      <div class="span6 exons_container">
        <div id="exons_from_task">
          <%= f.fields_for :exons do |exon_f| %>
            <%= render partial: "exon_fields", locals: { form_builder: exon_f } %>
          <% end %>
        </div>
      </div>

      <div class="span6">
        <div class="alert alert-info">
          The customizable parts will appear as you type in the material.
          <br /><br />
          For example if you type <b>$years_old$</b>, a form with the slug <b>years_old</b>
          will appear letting you select the appropriate Trait, say <b>Age</b>
          <br /><br />
          To trigger processing of this form, please unfocus from the material
          textarea, that is click anywhere else on the page
        </div>
        <div class="alert alert-info">
          Additional fields will appear if you select a Trait that has multiple
          options. You can use these fields to enter customized variations for
          each option.
        </div>
      </div>
    </div>
  </fieldset>

  <%= render partial: "questions_fieldset", locals: { form_builder: f,
    with_choices_labels: false, with_correct_checkboxes: true } %>

  <div class="span6 offset3">
    <%= f.submit( (@task.new_record? ? "Create" : "Update"),
      :class => "btn btn-large btn-primary") %>
  </div>
<% end %>


  <!-- hidden exons containers -->
  <div id="hidden_exons_from_task" class="hide"></div>

  <div class="hide">
    <select id="prop_traits">
      <%= options_from_collection_for_select Trait.all, :id, :name %>
    </select>

    <div id="prop_variations">
      <% Trait.with_options.each do |trait| %>
        <div class="trait" data-id=<%= trait.id %>>
          <% trait.options.each do |option| %>
            <input type="hidden" class="option"
              data-id="<%= option.id %>" data-value="<%= option.value %>" />
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <%= javascript_tag do %>
    preview_traits = <%= raw @preview_traits.to_json %>
  <% end %>

app/views/tasks/show.html.erb
<div class="row-fluid">
  <div class="span2"></div>
  <div class="span8">
    <h1><%= @task.name %></h1>
    <div class="task_material well">
      <%= @task.personalize_content_for_user(current_user).html_safe %>
    </div>
  </div>
</div>

<%= form_for(current_user, url: answer_task_user_path(current_user)) do |f| %>
  <div class="row-fluid question_row">
    <div class='span2'></div>
    <% @task.questions.each.with_index do |question, idx| %>
      <div class="span4">
        <h5>
          Q<%= idx+1 %>.
          <%= question.personalize_content_for_user(current_user) %>
        </h5>
        <% answer_counter = 97; #TODO: this is ugly ! %>
        <%= f.fields_for :answers, @answers[question.id] do |answer_f| %>
          <div>
            <%= answer_f.hidden_field :choice_id %>
            <%= answer_f.hidden_field :question_id %>
            <%= answer_f.check_box :keep_or_create %>
            (<%= answer_counter.chr.capitalize %>)
            <%= answer_f.object.choice.personalize_content_for_user(current_user) %>
            <% answer_counter += 1 %>
          </div>
        <% end %>
      </div>
      <%= "</div><div class='row-fluid'><div class='span2'></div>".html_safe if idx != 0 and idx % 2 == 1 %>
    <% end %>
  </div>

<div class="row-fluid answer_task_submit">
  <div class="span10">
    <%= hidden_field :task, :id %>
    <%= f.submit( "Submit", :class => "btn btn-large btn-primary pull-right") %>
  </div>
</div>

<% end %>