config/routes.rb
PersonalizedLearning::Application.routes.draw do

  resources :users, only: [:new, :show, :create, :destroy, :edit, :update] do
    member do
      put :answer_task
      put :answer_questionnaire
      get :edit_traits
      put :update_traits
      get :move_to_next_step
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks
  resources :traits, only: [:new, :edit, :update, :create, :destroy]
  resources :questionnaires
  match "/answers_for_tasks", to: "answers#for_tasks"
  match "/answers_for_questionnaires", to: "answers#for_questionnaires"

  root :to => 'sessions#new'

  match '/home', to: "users#home"
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/admin',   to: 'admin#home'

end

app/views/admin/home.html.erb
<h1>Admin Home</h1>

<div class="row-fluid admin-page">

  <div class="span3">
    <h2> Users </h2>
    <ul>
      <% @users.each do |user| %>
        <li><i class="icon-user"></i>
          <a href="<%= user_path(user) %>">
            <%= user.login %> (<%= user.step.nil? ? "no step" : user.step.name %>)
            <i class="icon-eye-open"></i>
          </a>
          <a href="<%= edit_user_path(user) %>"><i class="icon-edit"></i></a>
          <a href="<%= user_path(user) %>" data-confirm="Are you sure you want to delete this user ?"
            data-method="delete" rel="nofollow"><i class="icon-remove"></i></a>
        </li>
      <% end %>
      <li> <a href="<%= new_user_path %>" class="btn">New user <i class="icon-user"></i></a></li>
    </ul>
  </div>

  <div class="span3">
    <h2> Traits </h2>
    <ul>
      <% @traits.each do |trait| %>
        <li><i class="icon-headphones"></i>
          <%= trait.one_line_name %>
          <a href="<%= edit_trait_path(trait) %>"><i class="icon-edit"></i></a>
          <a href="<%= trait_path(trait) %>" data-confirm="Are you sure you want to delete this trait ?"
            data-method="delete" rel="nofollow"><i class="icon-remove"></i></a>
        </li>
      <% end %>
      <li> <a href="<%= new_trait_path %>" class="btn">New trait <i class="icon-headphones"></i></a></li>
    </ul>
  </div>

  <div class="span3">
    <h2> Tasks </h2>
    <ul>
      <% @tasks.each do |task| %>
        <li><i class="icon-align-center"></i>
          <%= "[#{task.step.name}]" if !task.step.nil? %>
          <a href="<%= task_path(task) %>">
            <%= task.name %>
            <%= "✓" if task.is_finalized? %>
            <i class="icon-eye-open"></i>
          </a>
          <a href="<%= edit_task_path(task) %>"><i class="icon-edit"></i></a>
          <a href="<%= task_path(task) %>" data-confirm="You sure 100% ?"
            data-method="delete" rel="nofollow"><i class="icon-remove"></i></a>
        </li>
      <% end %>
      <li> <a href="<%= new_task_path %>" class="btn">New task <i class="icon-align-center"></i></a></li>
    </ul>
  </div>

  <div class="span3">
    <h2> Questionnaires </h2>
    <ul>
      <% @questionnaires.each do |questionnaire| %>
        <li><i class="icon-question-sign"></i>
          <a href="<%= questionnaire_path(questionnaire) %>"><%= questionnaire.name %> <i class="icon-eye-open"></i></a>
          <a href="<%= edit_questionnaire_path(questionnaire) %>"><i class="icon-edit"></i></a>
          <a href="<%= questionnaire_path(questionnaire) %>"
            data-confirm="Are you sure you want to delete this questionnaire ?"
            data-method="delete" rel="nofollow"><i class="icon-remove"></i></a>
        </li>
      <% end %>
      <li> <a href="<%= new_questionnaire_path %>" class="btn">New questionnaire <i class="icon-question-sign"></i></a></li>
    </ul>
  </div>

</div>

<div class="row-fluid admin-page">
  <div class="span12">
    Download answers in CSV format :
    <ul>
      <li>
        <%= link_to "from all tasks", "/answers_for_tasks.csv" %>
      </li>
      <li>
        <%= link_to "from all questionnaires", "/answers_for_questionnaires.csv" %>
      </li>
    </ul>
  </div>
</div>

app/views/admin/index.html.erb
<h1>Admin Home</h1>

<div class="row-fluid admin-page">

  <div class="span4">
    <h2> Users </h2>
    <ul>
      <% @users.each do |user| %>
        <li><i class="icon-user"></i>
          <%= link_to user.login, user %>
          (<%= link_to "delete", user, method: :delete,
            data: { confirm: "You sure 100% ?" } %>)
        </li>
      <% end %>
      <li> <a href="<%= new_user_path %>" class="btn">New user <i class="icon-user"></i></a></li>
    </ul>
  </div>

  <div class="span4">
    <h2> Traits </h2>
    <ul>
      <% @traits.each do |trait| %>
        <li><i class="icon-headphones"></i>
          <%= link_to trait.one_line_name, edit_trait_path(trait) %>
          <a href="<%= trait_path(trait) %>" data-confirm="You sure 100% ?"
            data-method="delete" rel="nofollow"><i class="icon-remove"></i></a>
        </li>
      <% end %>
      <li> <a href="<%= new_trait_path %>" class="btn">New trait <i class="icon-headphones"></i></a></li>
    </ul>
  </div>

  <div class="span4">
    <h2> Tasks </h2>
    <ul>
      <% @tasks.each do |task| %>
        <li><i class="icon-align-center"></i>
          <%= link_to task.name, edit_task_path(task) %>
          <a href="<%= task_path(task) %>" data-confirm="You sure 100% ?"
            data-method="delete" rel="nofollow"><i class="icon-remove"></i></a>
        </li>
      <% end %>
      <li> <a href="<%= new_task_path %>" class="btn">New task <i class="icon-align-center"></i></a></li>
    </ul>
  </div>

</div>