config/routes.rb
PersonalizedLearning::Application.routes.draw do

  resources :users, only: [:new, :show, :create, :destroy, :edit, :update] do
    member do
      put :answer_task
      put :answer_questionnaire
      get :edit_traits
      put :update_traits
      get :move_to_next_step
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks
  resources :traits, only: [:new, :edit, :update, :create, :destroy]
  resources :questionnaires
  match "/answers_for_tasks", to: "answers#for_tasks"
  match "/answers_for_questionnaires", to: "answers#for_questionnaires"

  root :to => 'sessions#new'

  match '/home', to: "users#home"
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/admin',   to: 'admin#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :is_admin, :login, :step_id, :material_type, :user_traits_attributes, :answers_attributes

  before_save :create_remember_token

  has_many :user_traits, dependent: :destroy

  validates :login, presence: true, uniqueness: true

  accepts_nested_attributes_for :user_traits

  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, :allow_destroy => true

  scope :students, where(is_admin: [false, nil])

  belongs_to :step

  validates_inclusion_of :material_type, :in => %w(personalized traditional)

  def current_tasks(options={})
    tasks = Task.where(step_id: step_id, is_finalized: true)
    current_objects(tasks, options)
  end

  def current_questionnaires(options={})
    questionnaires = Questionnaire.where(step_id: step_id)
    current_objects(questionnaires, options)
  end

  def next_step
    Step.where("sequence_order > ?", step.sequence_order).first
  end

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end

    # objects are Tasks or Questionnaires
    def current_objects(objects, options={})
      if !options[:all]
        objects.reject! do |object|
          questions_count = object.questions.count
          answers_count = object.questions.map { |question|
            question.answers.where(user_id: self.id).count
          }.sum
          puts "reject ? #{questions_count == answers_count}"
          questions_count == answers_count
        end
      end
      objects
    end

end

app/controllers/users_controller.rb
include UserTraitsHelper

class UsersController < ApplicationController
  before_filter :admin_user, only: [:new, :edit, :update, :create, :show, :destroy]
  before_filter :user_signed_in, only: [:edit_traits, :update_traits, :answer_task, :home, :move_to_next_step]
  before_filter :correct_user, only: [:edit_traits, :update_traits, :answer_task, :answer_questionnaire, :move_to_next_step]

  def new
    @user = User.new
    render :edit
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "User #{@user.login} created successfully"
      redirect_to admin_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find params[:id]
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to admin_path
  end

  def edit_traits
    fill_user_traits @user
  end

  def update_traits
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to home_path
    else
      render :edit_traits
    end
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes(params[:user])
      flash[:success] = "User updated"
      redirect_to admin_path
    else
      render :edit
    end
  end

  def move_to_next_step
    @user = User.find params[:id]
    if !@user.next_step.nil? and @user.update_attributes(step_id: @user.next_step.id)
      flash[:success] = "Successfully moved to next step !"
      sign_in @user
    end
    redirect_to home_path
  end

  def home
    @tasks = current_user.current_tasks
    if !@tasks.empty?
      redirect_to @tasks.first
    else
      @questionnaires = current_user.current_questionnaires
      if !@questionnaires.empty?
        redirect_to @questionnaires.first
      end
    end
  end

  def answer_task
    @task = Task.find(params[:task][:id])
    answer @task, "tasks/show"
  end

  def answer_questionnaire
    @questionnaire = Questionnaire.find(params[:questionnaire][:id])
    answer @questionnaire, "questionnaires/show"
  end

  private

    def answer object, template
      if object.nil? or params[:user][:answers_attributes].nil?
        redirect_to :back
      else
        params[:user][:answers_attributes].each do |id, answer|
          if answer[:keep_or_create] == "0"
            params[:user][:answers_attributes][id][:_destroy] = "1"
          end
          params[:user][:answers_attributes][id].delete :keep_or_create
        end
        if @user.update_attributes(params[:user])
          flash[:success] = "Answer submitted"
          sign_in @user
          redirect_to home_path
        else
          render template
        end
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1><%= @user.new_record? ? "New user" : "Edit user" %></h1>

<div class="row-fluid">
  <div class="span12">
    <%= form_for(@user, :html => {:class => "form-horizontal"}) do |f| %>

      <%= render 'shared/error_messages', {object: @user} %>

      <div class="control-group">
        <%= f.label :login, :class => "control-label" %>
        <div class="controls">
          <%= f.text_field :login %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :material_type, :class => "control-label" %>
        <div class="controls">
          <%= f.select :material_type, %w(traditional personalized) %>
        </div>
      </div>

      <div class="control-group">
        <%= f.label :step_id, "Current step", :class => "control-label" %>
        <div class="controls">
          <%= f.collection_select :step_id, Step.all, :id, :name %>
        </div>
      </div>

      <div class="control-group">
        <div class="controls">
          <%= f.submit( (@user.new_record? ? "Create" : "Update"),
            :class => "btn btn-large btn-primary") %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/users/edit_traits.html.erb
<h1>Edit my Profile</h1>

<div class="row-fluid">
  <div class="span12">

    <div class="alert alert-info">
      Note : All fields are required.
    </div>


    <%= form_for(@user, url: update_traits_user_path(@user), :html => {:class => "form-horizontal"}) do |f| %>

      <%= render 'shared/error_messages', {object: @user} %>

      <% @user.user_traits.ordered_name.each do |ut| %>
        <%= f.fields_for :user_traits, ut do |ff| %>
          <div class="control-group">
            <% if ff.object.options.empty? %>
              <%= ff.label :value, ff.object.name, :class => "control-label" %>
              <div class="controls">
                <%= ff.text_field :value %>
              </div>
            <% else %>
              <%= ff.label :option_id, ff.object.name, :class => "control-label" %>
              <div class="controls">
                <%= ff.collection_select :option_id, ff.object.options, :id, :value %>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>

      <div class="control-group">
        <div class="controls">
          <%= f.submit "Update", class: "btn btn-large btn-primary" %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/users/home.html.erb
<h1>Home</h1>

<div class="row-fluid">
  <div class="span12">

    <% if (!@tasks or @tasks.empty?) and !@questionnaire %>
      <% if current_user.step.sequence_order == 1 %>
        For now on, you only have to fill up your profile :
        <%= link_to "here", edit_traits_user_path(current_user) %> <br />
        That's it !<br /></br />
      <% end %>

      <% if !current_user.next_step.nil? %>
        You have finished this step, congratulations !
        <span class="pull-right">
          Please confirm with us and click there :
          <%= link_to("Next Step", move_to_next_step_user_path(current_user), "class" => "btn btn-large btn-primary" ) %>
        </span>
      <% elsif current_user.step.sequence_order > 1 %>
        You have finished the experiment ! thank you for participating :)
      <% end %>

    <% else %>

      <% if @tasks %>
        <% if @tasks.size > 1 %>
          Please perform all of these tasks :
          <ul>
            <% @tasks.each do |task| %>
              <li>
                <%= link_to task.name, task %>
              </li>
            <% end %>
          </ul>
        <% elsif @tasks.size == 1 %>
          Please perform this <%= link_to "task", @tasks.first %>.
        <% end %>
      <% end %>

      <% if @questionnaires.size == 1 %>
          Please fill up this <%= link_to "questionnaire", @questionnaires.first %>.
      <% end %>

    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<h1> User <%= @user.login %> </h1>

<h2> Profile Traits : </h2>
<ul>
</ul>


<h2> Completed Tasks : </h2>

<ul>
</ul>