config/routes.rb
PersonalizedLearning::Application.routes.draw do

  resources :users, only: [:new, :show, :create, :destroy, :edit, :update] do
    member do
      put :answer_task
      put :answer_questionnaire
      get :edit_traits
      put :update_traits
      get :move_to_next_step
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :tasks
  resources :traits, only: [:new, :edit, :update, :create, :destroy]
  resources :questionnaires
  match "/answers_for_tasks", to: "answers#for_tasks"
  match "/answers_for_questionnaires", to: "answers#for_questionnaires"

  root :to => 'sessions#new'

  match '/home', to: "users#home"
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/admin',   to: 'admin#home'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://twitter.com/dongheeH">Donghee Hong</a>
    & <a href="http://adipasquale.github.com">Adrien Di Pasquale</a>,
    Online Learning & Communication 2012 Course @ <a href="http://www.kaist.ac.kr">KAIST</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   'https://github.com/adipasquale/personalized_learning#readme' %></li>
      <li><%= link_to "Contact", 'mailto:adrien.dipasquale@gmail.com' %></li>
    </ul>
  </nav>
  <div class="clear"></div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar <%= "user_connected" if signed_in? %>">
  <div class="navbar-inner step_<%= current_user.step.sequence_order if signed_in? %>">
    <div class="container-fluid">
      <div>
        <a href="<%= root_path %>" id= "logo" class="brand">
          <%= image_tag("stolen_logo_40.png") %>
          Personalized Learning
          <span class='step'>
            <%= "<#{current_user.step.name}>" if current_user %>
          </span>
        </a>
        <nav>
          <% if signed_in? %>
            <ul class="nav pull-right">
                <% if current_user.is_admin? %>
                  <li><a href="<%= admin_path %>">
                    <i class="icon-leaf icon-white"></i>Admin Home</a>
                  </li>
                <% else %>
                  <li><a href="<%= home_path %>">
                    <i class="icon-play icon-white"></i>Resume Experiment</a>
                  </li>
                  <li><a href="<%= edit_traits_user_path(current_user) %>">
                    <i class="icon-user icon-white"></i>My Profile</a>
                  </li>
                <% end %>
                <li><a href="<%= signout_path %>" data-method="delete" rel="nofollow">
                  <i class="icon-off icon-white"></i>Sign out</a>
                </li>
            </ul>
            <p class="navbar-text pull-right">Hello
              <span class="user_login">
                <%= current_user.login %> <%= " (admin)" if current_user.is_admin? %>
              </span>
              !
            </p>
          <% end %>
        </nav>
        <div class="clear"></div>
      </div>
    </div>
  </div>
</header>

<% if signed_in? %>
  <div class="container-fluid breadcrumbs-wrapper">
    <div class="breadcrumbs">
      <ul>
        <% Step.all.each do |step| %>
          <li class="step_<%= step.sequence_order %> <%= "selected" if current_user.step == step %>">
            <div class="triangle"></div>
            <div class="content"><%= step.name %></div>
          </li>
        <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Personalized Learning</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/header' %>

    <div class="container-fluid">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>

      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>